![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [1]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print("POP")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [3]:
# TESTANDO
S = Stack()

In [5]:
S.print_stack()

[]


In [7]:
S.push(1)

PUSH 1


In [9]:
S.push(2)

PUSH 2


In [11]:
S.push(3)

PUSH 3


In [13]:
S.print_stack()

[1, 2, 3]


In [15]:
S.pop()

POP


3

In [17]:
S.pop()

POP


2

In [19]:
S.print_stack()

[1]


In [21]:
S.push(7)

PUSH 7


In [23]:
S.push(8)

PUSH 8


In [25]:
S.push(9)

PUSH 9


In [27]:
S.print_stack()

[1, 7, 8, 9]


In [29]:
print(S.is_empty())

False


### Segunda Implementação

In [31]:
import numpy as np

In [33]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            self.__valores[self.__topo] = 0
            self.__topo -= 1
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [35]:
pilha = Pilha(5)

In [37]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [39]:
pilha.ver_topo()

-1

In [41]:
pilha.empilhar(1)
pilha.ver_topo()

1

In [43]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [45]:
pilha.imprime_pilha()

[1 1 2 3 4]


In [47]:
pilha.empilhar(6)

A pilha está cheia


In [49]:
pilha.ver_topo()

4

In [51]:
pilha.desempilhar()

In [53]:
pilha.ver_topo()

3

In [55]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

In [57]:
pilha.ver_topo()

1

In [59]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [61]:
pilha.desempilhar()

In [63]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [65]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [ ]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [ ]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

### Fim Teoria Aula 6